### ISSUE TITLE
Why the switch to Kafka?

### ISSUE THREAD

**Issue by jd327** [crccheck/kinesis-streams#44]
> NOTE: Kinesis was a bad idea, and we're switching to Kafka. So I won't be using my own library for much longer.

Can you elaborate on why Kinesis did not work out for you?

**Comment by crccheck** [comment]
Copy pasted from https://github.com/crccheck/kinesis-streams/commit/a9025ceb5dc7fdec248b000e175c7ec8f390134a#r31209617

Of course applications will differ, but Kinesis for non-JVM is just so hard to do. It's really low-level, and it seems like you need to wrap it in the [Kinesis Client Library](https://docs.aws.amazon.com/streams/latest/dev/developing-consumers-with-kcl.html) to get a friendly abstraction. This project is a pure Node attempt to wrap it up, but there are still lots of gaps.

With Kinesis, to get good performance you need to have lots of capacity and shards. But when you have multiple shards, the complexity goes way up, and this library doesn't really handle that. 

They way they calculate rate limits is so weird now. I'm running a lean Kinesis stream right now, but I keep getting provision exceeded. There's all sorts of weird rules for what your rate limit actually is that resembles filing taxes.

Kafka doesn't have any of those problems, but then you have to maintain Kafka.

**Comment by jd327** [comment]
Perfect. Thank you 👍

**Comment by Whoaa512** [comment]
@crccheck Just a curious follow up, would the same concerns you've listed here apply if instead you collected the data via the [Kinesis Agent](https://docs.aws.amazon.com/firehose/latest/dev/writing-with-agents.html)?

Seems like you could combine that w/ a streaming file logger and achieve similar results to using Kafka while still keeping the benefits of using the managed Kinesis service.

**Comment by crccheck** [comment]
That would solve a lot of these problems, but I didn't want a Java dependency locally.

**Comment by Whoaa512** [comment]
Makes sense, thank you 😄
